version: '3'

services:

  elasticsearch:
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    ports:
      - 9200:9200
    restart: unless-stopped
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:rw

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.13.1
    user: root
    depends_on:
      - elasticsearch
    command: filebeat -e -E output.elasticsearch.username=elastic -E output.elasticsearch.password=changeme -strict.perms=false
    hostname: filebeat
    restart: unless-stopped
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ../log:/opt/docker/log

  kibana:
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_PASSWORD: changeme
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
    image: docker.elastic.co/kibana/kibana:7.13.1
    ports:
      - 5601:5601
    restart: unless-stopped

volumes:
  elasticsearch:
    driver: local
  app-logs:
